### ISSUE TITLE
Can you add RootSettings.plist just like you did with the screen resolution?

### ISSUE THREAD

**Issue by chasefromm17** [benjibobs/async_wake#15]

**Comment by chasefromm17** [comment]
https://github.com/chasefromm17/RootSettings_for_iOS11 < see that for other details please, sorry if that's confusing :/

**Comment by JustAnotherC0der** [comment]
What exactly is this...?

**Comment by benjibobs** [comment]
There is no need to seeing the advancements made in other async forks. Maybe in the future if I feel that people are still using this though!
