### ISSUE TITLE
README missing inside /async_wake_ios

### ISSUE THREAD

**Issue by dallasgroot** [benjibobs/async_wake#2]
The README file is missing inside async_wake_ios folder, but removing it from the files tab on the left of Xcode, or putting it the folder makes the build run... :)

**Comment by benjibobs** [comment]
This issue returned after merging the NC fork. Am about to fix with shell support

**Comment by dallasgroot** [comment]
excellent! thats what I figured, was using NC fork before and had the same issue :)

**Comment by benjibobs** [comment]
Should be fixed. Turns out the netcat implementation was broken anyway!
