### ISSUE TITLE
iPA Form?

### ISSUE THREAD

**Issue by 32two64** [benjibobs/async_wake#4]
Is it possible in anyway to build this into an iPA file. I would do it myself if I had mac os x.

**Comment by IMcD23** [comment]
I’m sure once this project is closer to being useful without a debugger/Xcode, an IPA will be made. As it is right now, there is no use for this project aside from kernel debugging.

**Comment by benjibobs** [comment]
As @IMcD23 says, there is no current use for this in IPA form, it does not even spawn a shell yet.

**Comment by dallasgroot** [comment]
@32two64 an earlier build had shell temp working, but would just crash the shell once something connected to i

**Comment by benjibobs** [comment]
@dallasgroot @32two64 this was because we weren't and aren't yet running as root/uid=0
