### ISSUE TITLE
iOS 11.0.3

### ISSUE THREAD

**Issue by Dry05** [benjibobs/async_wake#7]
I can’t get to the kernel debugger, could you add offsets for iOS 11.0.3? I’m on iPhone 9,3.

**Comment by simsdj** [comment]
I don’t get the kernel debugger either on 10,3 11.1.2

**Comment by benjibobs** [comment]
I have not looked into the kernel debugger yet, but as it stands it supports iPhone 10, iPhone 7, iPhone 7 plus, iPhone 6S, iPhone 6 plus, iPod Touch 6G on iOS 11.1.2.

Feel free to create a pull request with new offsets, or to open an issue if some are incorrect
